apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/danielVargasBUK/argocd-basics-private.git
  password: your-github-personal-access-token
  username: your-github-personal-access-token-username