apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/danielVargasBUK
  password: your-github-personal-access-token
  username: your-github-personal-access-token-username